name: continuous integration workflow

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [ 12]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run:
          yarn install

      - name: build
        run:
          yarn run vscode:prepublish
          

      #- name: test
      #  run:
      #    npm run coverage
